# Generated by Django 4.2.7 on 2024-07-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_deliverycouriers_url_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='outdoor_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/outdoor/backgrounds/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='outdoor_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/outdoor/'),
        ),
    ]
