# Generated by Django 4.2.7 on 2024-07-10 15:33

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_gallery_outdoor_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='outdoor_background_image',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='outdoor_image',
            field=models.FileField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
