# Generated by Django 4.2.7 on 2024-07-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_category_options_remove_gallery_outdoor_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
