# Generated by Django 4.2.7 on 2024-07-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_product_product_color_product_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='address',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='city',
            new_name='billing_city',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='country',
            new_name='billing_country',
        ),
        migrations.RenameField(
            model_name='cartorder',
            old_name='state',
            new_name='billing_state',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
