# Generated by Django 4.2.7 on 2024-07-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_cartorder_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/mobile/'),
        ),
    ]
