# Generated by Django 4.2.7 on 2024-08-01 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_remove_product_mobile_image_mobileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_images', to='store.product'),
        ),
    ]
