# Generated by Django 4.2.7 on 2024-08-01 14:47

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_mobileimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='mobile_image',
            field=models.FileField(blank=True, null=True, upload_to=userauths.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='product',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
