# Generated by Django 4.2.7 on 2024-07-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0002_rename_settings_configsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsettings',
            name='currency_abbreviation',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='configsettings',
            name='currency_sign',
            field=models.CharField(default='₹', max_length=10),
        ),
        migrations.AlterField(
            model_name='configsettings',
            name='service_fee_flat_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='NOTE: Add the amount you want to charge as service fee e.g $0.00', max_digits=12),
        ),
        migrations.AlterField(
            model_name='configsettings',
            name='service_fee_percentage',
            field=models.IntegerField(default=0, help_text='NOTE: Numbers added here are in percentage (%)ve.g 0%'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='rate',
            field=models.IntegerField(default=12, help_text='Numbers added here are in percentage (12 = 12%)'),
        ),
    ]
