# Generated by Django 4.2.7 on 2024-07-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0003_alter_configsettings_currency_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsettings',
            name='service_fee_flat_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='NOTE: Add the amount you want to charge as service fee e.g 0.00', max_digits=12),
        ),
    ]
