# Generated by Django 4.2.7 on 2024-07-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0004_alter_configsettings_service_fee_flat_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configsettings',
            name='service_fee_charge_type',
        ),
        migrations.RemoveField(
            model_name='configsettings',
            name='service_fee_flat_rate',
        ),
        migrations.RemoveField(
            model_name='configsettings',
            name='service_fee_percentage',
        ),
    ]
