# Generated by Django 4.2.7 on 2024-07-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addon', '0005_remove_configsettings_service_fee_charge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsettings',
            name='service_fee_charge_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('flat_rate', 'Flat Rate')], default='percentage', max_length=30),
        ),
        migrations.AddField(
            model_name='configsettings',
            name='service_fee_flat_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='NOTE: Add the amount you want to charge as service fee e.g 0.00', max_digits=12),
        ),
        migrations.AddField(
            model_name='configsettings',
            name='service_fee_percentage',
            field=models.IntegerField(default=0, help_text='NOTE: Numbers added here are in percentage (%)ve.g 0%'),
        ),
    ]
